version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - bot_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  bot_network:
    driver: bridge
